### ISSUE TITLE
problem with pyhton installation on MacOS M1

### ISSUE THREAD

**Issue by apenailillo** [lnds/codice#20]
following the current installation on the readme o the repository, on the command

`pipenv install --python `which python3.10.6``

this happens:

`pipenv install --python `which python3.10.6`
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/cli/options.py", line 57, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/cli/command.py", line 236, in install
    do_install(
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/core.py", line 2046, in do_install
    ensure_project(
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/core.py", line 525, in ensure_project
    ensure_virtualenv(
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/core.py", line 446, in ensure_virtualenv
    python = ensure_python(project, three=three, python=python)
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/core.py", line 335, in ensure_python
    path_to_python = find_a_system_python(python)
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/core.py", line 305, in find_a_system_python
    python_entry = find_python(finder, line)
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/utils/shell.py", line 301, in find_python
    result = finder.find_python_version(name=line)
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/vendor/pythonfinder/pythonfinder.py", line 283, in find_python_version
    return self.system_path.find_python_version(
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/vendor/pythonfinder/pythonfinder.py", line 115, in system_path
    self._system_path = self.create_system_path()
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/vendor/pythonfinder/pythonfinder.py", line 77, in create_system_path
    return pyfinder_path.SystemPath.create(
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 696, in create
    instance = instance._run_setup()
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 264, in _run_setup
    paths[p] = new_instance.get_path(p.joinpath(bin_dir))
  File "/opt/homebrew/Cellar/pipenv/2022.9.24/libexec/lib/python3.10/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 452, in get_path
    raise ValueError("Path not found or generated: {0!r}".format(path))
ValueError: Path not found or generated: PosixPath`

pipenv version: 

`pipenv --version
pipenv, version 2022.9.24`

changing the version of python to 3.8 don't change the outcome

**Comment by lnds** [comment]
aers

**Comment by lnds** [comment]
Fixed was a dependency on Psycopg2.
Remember to do `pipenv shell` on every terminal when yo try this.
I'm working on docker support, maybe is ready this week
